### ISSUE TITLE
在有Horizontal Pod Autoscaling情况下，无法完成目标扩容

### ISSUE THREAD

**Issue by fonzie1006** [AliyunContainerService/kubernetes-cronhpa-controller#10]
在使用过程中，发现deployment有Horizontal Pod Autoscaling的情况下，扩容出来的会被马上修改回去，因为在Horizontal Pod Autoscaling中已经定义了最大副本和最小副本数。而cronHPA修改的是deployment的副本数.

**Comment by ringtail** [comment]
@fonzie1006 这个问题目前已知，目前的解法是增加HPA为ScaleTarget，然后取两者之大为兼容。

**Comment by fonzie1006** [comment]
@ringtail  好的，后续我持续关注一下，取两者之大，如果HPA认为没有到需要扩容的时候，还是会被缩回去。后续应该会考虑有HPA的情况把，这个项目还是不错的。

**Comment by ringtail** [comment]
@fonzie1006 如果Target是HPA，有可能会调整Min和Max的设置。
