### ISSUE TITLE
cronhpa兼容hpa配置

### ISSUE THREAD

**Issue by k-kyle** [AliyunContainerService/kubernetes-cronhpa-controller#13]
**描述**: 一个deploy配置期望pod数量为20，同时绑定了hpa和cronhpa。
        cronhpa 配置deploy 在8:00伸缩pod数量到40，10点缩容到20;
        hpa配置期望deploy cpu使用率低于60%，minpods为20,maxpods为50

**现状**：
      早上8点的时候deploy会被伸缩到40,但是如果此时deploy负载很低,那么Pod数量将会受hpa控制，调整到合适的Pod数量。期望是可以配置在cronhpa范围内不受hpa控制。

**Comment by k-kyle** [comment]
针对以上问题，有两个临时方案

**Comment by k-kyle** [comment]
针对以上问题，有两个临时解决方案
1.写个定时脚本，8点前删除hpa配置,10后添加
2.同一个镜像启动两个deploy，一个deploy配置hpa，一个deploy配置cronhpa。业务同时连接两个deploy提供的svc

**Comment by ringtail** [comment]
move to v1.4.0

**Comment by ringtail** [comment]
*proposal*
1. TargetRef支持HPA对象
2. 扩容时cronhpa调整HPA对象的最小值为max(min replicas, cronhpa replicas, current replicas)
3. 缩容时cronhpa调整HPA对象的最小值为min(cronhpa replicas,current replicas)

**Comment by ist0ne** [comment]
这个功能什么时间能开发完成？

**Comment by ringtail** [comment]
> 这个功能什么时间能开发完成？

已经协调开发资源，本周开发中

**Comment by ist0ne** [comment]
好的，谢谢

**Comment by k-kyle** [comment]
> _proposal_
> 
> 1. TargetRef支持HPA对象
> 2. 扩容时cronhpa调整HPA对象的最小值为max(min replicas, cronhpa replicas, current replicas)
> 3. 缩容时cronhpa调整HPA对象的最小值为min(cronhpa replicas,current replicas)

哈哈，方法不错，比如cronhpa scale-up 到50个，把hpa的min replicas调整到50就行了，这样可以保证这段时间不会因为hpa减少replicas，但是要记得改之前的值呀，scale-down的时候把min replicas改回去。

**Comment by ringtail** [comment]
> > _proposal_
> > 
> > 1. TargetRef支持HPA对象
> > 2. 扩容时cronhpa调整HPA对象的最小值为max(min replicas, cronhpa replicas, current replicas)
> > 3. 缩容时cronhpa调整HPA对象的最小值为min(cronhpa replicas,current replicas)
> 
> 哈哈，方法不错，比如cronhpa scale-up 到50个，把hpa的min replicas调整到50就行了，这样可以保证这段时间不会因为hpa减少replicas，但是要记得改之前的值呀，scale-down的时候把min replicas改回去。

OK

**Comment by huoji1990** [comment]
这个功能何时能够正式上线

**Comment by ringtail** [comment]
> 这个功能何时能够正式上线

开发基本完成，测试中，预计1月17日前上线

**Comment by huoji1990** [comment]
> > 这个功能何时能够正式上线
> 
> 开发基本完成，测试中，预计1月17日前上线

期待中，这个功能完全命中当前需求。

**Comment by MidTin** [comment]
这个 PR 什么时候能发布？

**Comment by ringtail** [comment]
> 这个 PR 什么时候能发布？

PR已经基本完成，全量场景测试中，部分分支逻辑有些需要讨论下，可以在上面的PR里面跟进。
