### ISSUE TITLE
cronhpa目前能否直接支持在某一时间点之后，开始定时扩缩

### ISSUE THREAD

**Issue by cugykw** [AliyunContainerService/kubernetes-cronhpa-controller#33]
#### 问题描述：
cronhpa能否直接支持该场景，比如：在2020.01.01 14:00 之后，开始每隔一个小时执行一个定时任务？

**Comment by ringtail** [comment]
@cugykw 我建议分开来看，本身cronhpa支持excludeDates，可以将月份和时间做过滤，然后过了这个时间后再修改下。

**Comment by cugykw** [comment]
@ringtail 目前有一些方案，但是想问，目前的cronhpa本声而言暂不支持这个功能吗？也就是说还是要自己在封装一层，定时到了某个时间点，在开始提交定时扩缩任务？

**Comment by ringtail** [comment]
是这样的，cronhpa的表达方式crontab的格式，是定期任务类型的，如果你期望从哪天开始，需要结合excludeDates来实现，不过excludeDates的格式也是crontab，没有before和after的语义

**Comment by cugykw** [comment]
@ringtail 多谢，这确实是一种方案。
