### ISSUE TITLE
kubernetes-cronhpa-controller always auto restart

### ISSUE THREAD

**Issue by SecurityNeo** [AliyunContainerService/kubernetes-cronhpa-controller#34]
Hi,
  First,kubernetes-cronhpa-controller is a very  awesome project,thank you!
  Now a problem hit my head,and i need your help.The pod kubernetes-cronhpa-controller always auto restart,the log looks like this:
W1210 16:48:18.909168       1 reflector.go:289] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: watch of *v1beta1.CronHorizontalPodAutoscaler ended with: The resourceVersion for the provided watch is too old.
log: exiting because of error: log: cannot create log: open /tmp/kubernetes-cronhpa-controller.kubernetes-cronhpa-controller-79f478fff4-l7sbr.unknownuser.log.WARNING.20191210-164818.1: no such file or directory

look forward to your kind advice,3ks!

Best regards!
Neo

**Comment by ringtail** [comment]
Coud you provide the image version?

**Comment by SecurityNeo** [comment]
registry.cn-beijing.aliyuncs.com/acs/kubernetes-cronhpa-controller:v1.2.0

**Comment by ringtail** [comment]
I think you can try this one. https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/blob/master/config/deploy/deploy.yaml

**Comment by ringtail** [comment]
Is the error still there?

**Comment by SecurityNeo** [comment]
I still use thw image，and change the configuration of deployment，like this:

        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /tmp
          name: tmp
     ......
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: time
      - emptyDir: {}
        name: tmp

in other words,i mount the temp directory to emptyDir.it works!but why?

**Comment by ringtail** [comment]
The base image of v1.2.0 is scratch.  That's the point

**Comment by ringtail** [comment]
registry.aliyuncs.com/ringtail/kubernetes-cronhpa-controller:v1.3.0-8e82633c-aliyun should be better.

**Comment by ringtail** [comment]
So, Could I close this PR?

**Comment by SecurityNeo** [comment]
sure,thank you!
