### ISSUE TITLE
kubectl edit cronhorizontalpodautoscaler don't match the expected

### ISSUE THREAD

**Issue by HYmian** [AliyunContainerService/kubernetes-cronhpa-controller#6]
when I edit cronhorizontalpodautoscaler's `spec.scaleTargetRef.name`, corresponding 
 annotation should be updated

**Comment by ringtail** [comment]
Link to pr https://github.com/kubernetes/enhancements/pull/1265

**Comment by ringtail** [comment]
mark it as proposal
