### ISSUE TITLE
target not work after apply with new cron

### ISSUE THREAD

**Issue by yunzheyu** [AliyunContainerService/kubernetes-cronhpa-controller#60]
first i create cron as:
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-speech
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: speech
   jobs:
   - name: "scale-down-10"
     schedule: "30 0 0 * * *"
     targetSize: 10
   - name: "scale-down-80"
     schedule: "0 0 22 * * *"
     targetSize: 80
   - name: "scale-up-100"
     schedule: "0 30 06 * * *"
     targetSize: 100
   - name: "scale-up-200"
     schedule: "0 35 06 * * *"
     targetSize: 200
   - name: "scale-up-300"
     schedule: "0 40 06 * * *"
     targetSize: 300
   - name: "scale-up-400"
     schedule: "0 45 06 * * *"
     targetSize: 400
   - name: "scale-up-500"
     schedule: "0 50 06 * * *"
     targetSize: 500
   - name: "scale-up-600"
     schedule: "0 55 06 * * *"
     targetSize: 600
   - name: "scale-up-700"
     schedule: "0 0 07 * * *"
     targetSize: 700
after a few weeks i modify as and apply with no errors:
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-speech
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: speech
   jobs:
   - name: "scale-down-10"
     schedule: "30 0 0 * * *"
     targetSize: 10
   - name: "scale-down-80"
     schedule: "0 0 22 * * *"
     targetSize: 80
   - name: "scale-up-100"
     schedule: "0 30 06 * * *"
     targetSize: 100
   - name: "scale-up-200"
     schedule: "0 35 06 * * *"
     targetSize: 200
   - name: "scale-up-300"
     schedule: "0 40 06 * * *"
     targetSize: 300
   - name: "scale-up-400"
     schedule: "0 45 06 * * *"
     targetSize: 400
   - name: "scale-up-500"
     schedule: "0 50 06 * * *"
     targetSize: 500
   - name: "scale-up-600"
     schedule: "0 55 06 * * *"
     targetSize: 600
now , at 7:00 am i still have 700 pods
kubectl describe cronhpa state is Succeed not submitted
My version 1.3.3 appversion v1beta1

**Comment by ringtail** [comment]
Fix due to #63
