### ISSUE TITLE
Introduce go.mod

### ISSUE THREAD

**Issue by shindanim** [AliyunContainerService/kubernetes-cronhpa-controller#62]
Hi, all 

Thanks for working this fancy project. 
This is what I wanted exactly. 
I've been using this with docker build, and it's fine for me, 
but I've been also embarrassed because of absence of go.mod when I try to run unittest. 
**Is there any plan for adding go.mod** for managing go module dependency? 

BR, 
Dayoung Shin

**Comment by liuming-dev** [comment]
+1

**Comment by ringtail** [comment]
> Hi, all
> 
> Thanks for working this fancy project.
> This is what I wanted exactly.
> I've been using this with docker build, and it's fine for me,
> but I've been also embarrassed because of absence of go.mod when I try to run unittest.
> **Is there any plan for adding go.mod** for managing go module dependency?
> 
> BR,
> Dayoung Shin

Sure! I'll get it done this week. And we would like to bump the dependency to v1.18.

**Comment by shindanim** [comment]
Thanks for reply ! I hope I can contribute this repo sooner or later

**Comment by ringtail** [comment]
> I hope I

sure!

**Comment by ringtail** [comment]
@shindanim @liuming-dev Try the master branch. If any Q, ping me here.
