### ISSUE TITLE
support for scale-down to 0

### ISSUE THREAD

**Issue by ronwxy** [AliyunContainerService/kubernetes-cronhpa-controller#7]
setting targetSize to 0  did not take effect, one ECI instance running actually. Could you pls provide support for scale-down to 0 for deployment?

**Comment by ringtail** [comment]
https://github.com/kubernetes/kubernetes/issues/69687

**Comment by ringtail** [comment]
I prefer to wait for the offical implement.

**Comment by denverdino** [comment]
"scale to 0" has been covered in Knative. thx

**Comment by ringtail** [comment]
HPA scale to zero is support in k8s 1.16 with feature gates.

**Comment by ringtail** [comment]
@ronwxy And We would like to support this feature in k8s 1.16

**Comment by ringtail** [comment]
@ronwxy in  k8s 1.16. you can switch HPAScaleToZero feature gates and it should work.
