### ISSUE TITLE
Continuously delete and create cronhpa objects with the same name through JAVA API con't cancel previous task

### ISSUE THREAD

**Issue by 125964590** [AliyunContainerService/kubernetes-cronhpa-controller#73]
After I update the scales rules , the previous task was still executed.
![](https://tva1.sinaimg.cn/large/0081Kckwly1gksb9fduarj30t403tt9k.jpg)

**Comment by 125964590** [comment]
After I update the scales rules , the previous task was still executed.
![image](![](https://tva1.sinaimg.cn/large/0081Kckwly1gksb9fduarj30t403tt9k.jpg))

**Comment by ringtail** [comment]
Fix by #74
