### ISSUE TITLE
Cron running at unspecified times

### ISSUE THREAD

**Issue by rmohammed-xtime** [AliyunContainerService/kubernetes-cronhpa-controller#81]
I am running registry.aliyuncs.com/acs/kubernetes-cronhpa-controller:v1.3.0-7991d02c-aliyun

I have a cronhpa  that is scheduled to scale at  "0 0 21 * * ?" and at "0 30 3 * * ?" but I can see the scaling fire at times outside those ranges:

time="2020-12-28T00:38:05-08:00" level=info msg="pstsdran is handled by cron-hpa controller"
time="2020-12-28T00:38:05-08:00" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {pstsdran  prod /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran c88eeb56-e8e5-11ea-a21a-02023a7c8a8e 566609624 1 2020-08-27 21:20:19 -0700 PDT <nil> <nil> map[controller-tools.k8s.io:1.0] map[] [] nil []  []} {[] {apps/v1beta2 Deployment pstsdran} [{scale-down 0 0 21 * * ? false 0} {scale-up 0 30 3 * * ? false 1}]} {{apps/v1beta2 Deployment pstsdran} [] [{scale-down 3da528fb-3152-489c-b199-3789eff5aa43 0 0 21 * * ? 0 false Succeed 2020-12-27 21:00:01 -0800 PST cron hpa job scale-down executed successfully. current replicas:1, desired replicas:0.} {scale-up 063b159b-f90c-4b2c-9e17-93ec69a1f314 0 30 3 * * ? 1 false Succeed 2020-12-27 03:30:00 -0800 PST cron hpa job scale-up executed successfully. current replicas:0, desired replicas:1.}]}} has been handled completely."

time="2020-12-28T03:30:01-08:00" level=info msg="pstsdran is handled by cron-hpa controller"
time="2020-12-28T03:30:01-08:00" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {pstsdran  prod /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran c88eeb56-e8e5-11ea-a21a-02023a7c8a8e 566970436 1 2020-08-27 21:20:19 -0700 PDT <nil> <nil> map[controller-tools.k8s.io:1.0] map[] [] nil []  []} {[] {apps/v1beta2 Deployment pstsdran} [{scale-down 0 0 21 * * ? false 0} {scale-up 0 30 3 * * ? false 1}]} {{apps/v1beta2 Deployment pstsdran} [] [{scale-down 3da528fb-3152-489c-b199-3789eff5aa43 0 0 21 * * ? 0 false Succeed 2020-12-27 21:00:01 -0800 PST cron hpa job scale-down executed successfully. current replicas:1, desired replicas:0.} {scale-up 063b159b-f90c-4b2c-9e17-93ec69a1f314 0 30 3 * * ? 1 false Succeed 2020-12-28 03:30:01 -0800 PST cron hpa job scale-up executed successfully. current replicas:0, desired replicas:1.}]}} has been handled completely."

time="2020-12-28T10:38:05-08:00" level=info msg="pstsdran is handled by cron-hpa controller"
time="2020-12-28T10:38:05-08:00" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {pstsdran  prod /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran c88eeb56-e8e5-11ea-a21a-02023a7c8a8e 566970436 1 2020-08-27 21:20:19 -0700 PDT <nil> <nil> map[controller-tools.k8s.io:1.0] map[] [] nil []  []} {[] {apps/v1beta2 Deployment pstsdran} [{scale-down 0 0 21 * * ? false 0} {scale-up 0 30 3 * * ? false 1}]} {{apps/v1beta2 Deployment pstsdran} [] [{scale-down 3da528fb-3152-489c-b199-3789eff5aa43 0 0 21 * * ? 0 false Succeed 2020-12-27 21:00:01 -0800 PST cron hpa job scale-down executed successfully. current replicas:1, desired replicas:0.} {scale-up 063b159b-f90c-4b2c-9e17-93ec69a1f314 0 30 3 * * ? 1 false Succeed 2020-12-28 03:30:01 -0800 PST cron hpa job scale-up executed successfully. current replicas:0, desired replicas:1.}]}} has been handled completely."

time="2020-12-28T20:38:05-08:00" level=info msg="pstsdran is handled by cron-hpa controller"
time="2020-12-28T20:38:05-08:00" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {pstsdran  prod /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran c88eeb56-e8e5-11ea-a21a-02023a7c8a8e 566970436 1 2020-08-27 21:20:19 -0700 PDT <nil> <nil> map[controller-tools.k8s.io:1.0] map[] [] nil []  []} {[] {apps/v1beta2 Deployment pstsdran} [{scale-down 0 0 21 * * ? false 0} {scale-up 0 30 3 * * ? false 1}]} {{apps/v1beta2 Deployment pstsdran} [] [{scale-down 3da528fb-3152-489c-b199-3789eff5aa43 0 0 21 * * ? 0 false Succeed 2020-12-27 21:00:01 -0800 PST cron hpa job scale-down executed successfully. current replicas:1, desired replicas:0.} {scale-up 063b159b-f90c-4b2c-9e17-93ec69a1f314 0 30 3 * * ? 1 false Succeed 2020-12-28 03:30:01 -0800 PST cron hpa job scale-up executed successfully. current replicas:0, desired replicas:1.}]}} has been handled completely."

time="2020-12-28T22:04:07-08:00" level=info msg="pstsdran is handled by cron-hpa controller"
time="2020-12-28T22:04:07-08:00" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {pstsdran  prod /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran c88eeb56-e8e5-11ea-a21a-02023a7c8a8e 568073553 1 2020-08-27 21:20:19 -0700 PDT <nil> <nil> map[controller-tools.k8s.io:1.0] map[] [] nil []  []} {[] {apps/v1beta2 Deployment pstsdran} [{scale-down 0 0 21 * * ? false 0} {scale-up 0 30 3 * * ? false 1}]} {{apps/v1beta2 Deployment pstsdran} [] [{scale-down 3da528fb-3152-489c-b199-3789eff5aa43 0 0 21 * * ? 0 false Succeed 2020-12-28 22:04:07 -0800 PST cron hpa job scale-down executed successfully. current replicas:1, desired replicas:0.} {scale-up 063b159b-f90c-4b2c-9e17-93ec69a1f314 0 30 3 * * ? 1 false Succeed 2020-12-28 03:30:01 -0800 PST cron hpa job scale-up executed successfully. current replicas:0, desired replicas:1.}]}} has been handled completely."

time="2020-12-29T03:30:00-08:00" level=info msg="pstsdran is handled by cron-hpa controller"
time="2020-12-29T03:30:00-08:00" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {pstsdran  prod /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran c88eeb56-e8e5-11ea-a21a-02023a7c8a8e 568404908 1 2020-08-27 21:20:19 -0700 PDT <nil> <nil> map[controller-tools.k8s.io:1.0] map[] [] nil []  []} {[] {apps/v1beta2 Deployment pstsdran} [{scale-down 0 0 21 * * ? false 0} {scale-up 0 30 3 * * ? false 1}]} {{apps/v1beta2 Deployment pstsdran} [] [{scale-down 3da528fb-3152-489c-b199-3789eff5aa43 0 0 21 * * ? 0 false Succeed 2020-12-28 22:04:07 -0800 PST cron hpa job scale-down executed successfully. current replicas:1, desired replicas:0.} {scale-up 063b159b-f90c-4b2c-9e17-93ec69a1f314 0 30 3 * * ? 1 false Succeed 2020-12-29 03:30:00 -0800 PST cron hpa job scale-up executed successfully. current replicas:1, desired replicas:1.}]}} has been handled completely."

time="2020-12-29T06:38:05-08:00" level=info msg="pstsdran is handled by cron-hpa controller"
time="2020-12-29T06:38:05-08:00" level=info msg="&{{CronHorizontalPodAutoscaler autoscaling.alibabacloud.com/v1beta1} {pstsdran  prod /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran c88eeb56-e8e5-11ea-a21a-02023a7c8a8e 568404908 1 2020-08-27 21:20:19 -0700 PDT <nil> <nil> map[controller-tools.k8s.io:1.0] map[] [] nil []  []} {[] {apps/v1beta2 Deployment pstsdran} [{scale-down 0 0 21 * * ? false 0} {scale-up 0 30 3 * * ? false 1}]} {{apps/v1beta2 Deployment pstsdran} [] [{scale-down 3da528fb-3152-489c-b199-3789eff5aa43 0 0 21 * * ? 0 false Succeed 2020-12-28 22:04:07 -0800 PST cron hpa job scale-down executed successfully. current replicas:1, desired replicas:0.} {scale-up 063b159b-f90c-4b2c-9e17-93ec69a1f314 0 30 3 * * ? 1 false Succeed 2020-12-29 03:30:00 -0800 PST cron hpa job scale-up executed successfully. current replicas:1, desired replicas:1.}]}} has been handled completely."

apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  creationTimestamp: "2020-08-28T04:20:19Z"
  generation: 1
  labels:
    controller-tools.k8s.io: "1.0"
  name: pstsdran
  namespace: prod
  resourceVersion: "568404908"
  selfLink: /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/prod/cronhorizontalpodautoscalers/pstsdran
  uid: c88eeb56-e8e5-11ea-a21a-02023a7c8a8e
spec:
  excludeDates: null
  jobs:
  - name: scale-down
    runOnce: false
    schedule: 0 0 21 * * ?
    targetSize: 0
  - name: scale-up
    runOnce: false
    schedule: 0 30 3 * * ?
    targetSize: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: pstsdran
status:
  conditions:
  - jobId: 3da528fb-3152-489c-b199-3789eff5aa43
    lastProbeTime: "2020-12-29T06:04:07Z"
    message: cron hpa job scale-down executed successfully. current replicas:1, desired
      replicas:0.
    name: scale-down
    runOnce: false
    schedule: 0 0 21 * * ?
    state: Succeed
    targetSize: 0
  - jobId: 063b159b-f90c-4b2c-9e17-93ec69a1f314
    lastProbeTime: "2020-12-29T11:30:00Z"
    message: cron hpa job scale-up executed successfully. current replicas:1, desired
      replicas:1.
    name: scale-up
    runOnce: false
    schedule: 0 30 3 * * ?
    state: Succeed
    targetSize: 1
  excludeDates: null
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: pstsdran

**Comment by ringtail** [comment]
Pls upgrade the version to the latest one. You can view the full process in the log and ops view.

**Comment by ringtail** [comment]
This image `v1.3.0-7991d02c-aliyun` has one bug. Fix by #78

**Comment by ringtail** [comment]
It's easy to ensure a time schedule execution with the latest version. You can view the schedule in queue from ops view.[https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/pull/76] and check execution log from container.

**Comment by rmohammed-xtime** [comment]
Thanks. The new version will help debug the problem.

Incidentally the problem affects my other cronhpa jobs randomly. I just showed one example in my issue description
