### ISSUE TITLE
cronhpa can not work for openKruise workload cloneSet

### ISSUE THREAD

**Issue by weiyuanzhuang** [AliyunContainerService/kubernetes-cronhpa-controller#82]
env：
kubernetes： 1.17
openKruise： 0.7.0
cronhpa: 0.3.0

create a cloneSet object with replicas 2
create a cronhpa to scale up to 8 with 30seconds

[root@sz02 ~]# kubectl -n project-16047 get cronhpa
NAME                            AGE
work-platform-server-prd-2805   17h
[root@sz02 ~]# kubectl -n project-16047 get clonesets.apps.kruise.io work-platform-server-prd-2805
NAME                            DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
work-platform-server-prd-2805   2         2         2               2       2       7d15h

cronhpa yaml as follow :
######################
```
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling.alibabacloud.com/v1beta1","kind":"CronHorizontalPodAutoscaler","metadata":{"annotations":{},"name":"work-platform-server-prd-2805","namespace":"project-16047"},"spec":{"jobs":[{"name":"scale-up","runOnce":false,"schedule":"0 */1 * * * *","targetSize":8}],"scaleTargetRef":{"apiVersion":"apps.kruise.io/v1alpha1","kind":"CloneSet","name":"work-platform-server-prd-2805"}}}
  creationTimestamp: "2021-01-04T13:19:56Z"
  generation: 1321
  name: work-platform-server-prd-2805
  namespace: project-16047
  resourceVersion: "12351179"
  selfLink: /apis/autoscaling.alibabacloud.com/v1beta1/namespaces/project-16047/cronhorizontalpodautoscalers/work-platform-server-prd-2805
  uid: 19320f6d-99ed-4571-91b5-c73a9fcf49a3
spec:
  excludeDates: null
  jobs:
  - name: scale-up
    runOnce: false
    schedule: 0 */1 * * * *
    targetSize: 8
  scaleTargetRef:
    apiVersion: apps.kruise.io/v1alpha1
    kind: CloneSet
    name: work-platform-server-prd-2805
status:
  conditions:
  - jobId: 48682d66-e7d3-46c6-b122-377ea9577470
    lastProbeTime: "2021-01-05T11:18:00Z"
    message: cron hpa failed to execute,because of Failed to found source target work-platform-server-prd-2805
    name: scale-up
    runOnce: false
    schedule: 0 */1 * * * *
    state: Failed
    targetSize: 8
  excludeDates: null
  scaleTargetRef:
    apiVersion: apps.kruise.io/v1alpha1
    kind: CloneSet
    name: work-platform-server-prd-2805
```
#####################################

the output error is "cron hpa failed to execute,because of Failed to found source target work-platform-server-prd-2805"

is it can not support openkruise now? but I found in other issue, it  might support advance statefulSet in openKruise
[ https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/issues/55](url)

**Comment by ringtail** [comment]
If the workloads implement the scale subresource interface. It should be fine for CronHPA.

**Comment by ringtail** [comment]
Could you try the latest version of CronHPA on github.

**Comment by weiyuanzhuang** [comment]
> Could you try the latest version of CronHPA on github.

yes ， I found it worked for the latest version, thanks for reply
