### ISSUE TITLE
Incorrect time in Go process

### ISSUE THREAD

**Issue by rmohammed-xtime** [AliyunContainerService/kubernetes-cronhpa-controller#83]
It appears the Go process has a problem with daylight saving time even though the container has the correct time. This leads to jobs not executing at correct times. The ops view does not show the current time.

I am using registry.aliyuncs.com/acs/kubernetes-cronhpa-controller:v1.4.0-fc4f6060-aliyun with
 - env:
    - name: TZ
       value: America/Los_Angeles

$ kubectl -n stg4 apply -f cronhpa.yaml
cronhorizontalpodautoscaler.autoscaling.alibabacloud.com/xwsbatch created
...
$ kubectl -n kube-system logs kubernetes-cronhpa-controller-c88f565-gqm76 | grep batch
...
0126 16:42:56.737033       1 cronmanager.go:58] cronHPA job scale-up of cronHPA xwsbatch in stg4 created, 133 active jobs exist
I0126 16:42:56.744888       1 cronhorizontalpodautoscaler_controller.go:75] Start to handle cronHPA xwsbatch in stg4 namespace
$ kubectl -n kube-system exec -it kubernetes-cronhpa-controller-c88f565-gqm76 -- date
Tue Jan 26 15:44:55 PST 2021
$ date
Tue Jan 26 15:46:35 PST 2021

**Comment by ringtail** [comment]
@rmohammed-xtime I'll check it.

**Comment by ringtail** [comment]
@rmohammed-xtime cron-engine use the timezone in env as default. we will fix this issue in next version this month.

**Comment by ringtail** [comment]
link to the same issue. https://github.com/robfig/cron/issues/289

**Comment by smoke** [comment]
@ringtail is the issue fixed?

**Comment by ringtail** [comment]
> @ringtail is the issue fixed?

I think it has been done.
