### ISSUE TITLE
Use the same crontab expression as cronjob

### ISSUE THREAD

**Issue by lidajia** [AliyunContainerService/kubernetes-cronhpa-controller#91]
Currently， Cronhpa using crontab ‘Second | Minute | Hour | Dom | Month | DowOptional | Descriptor ’, the CronJob using 'Minute | Hour | Dom | Month | Dow | Descriptor'。It is good to unify the crontab spec。 We can provide unified UI controls for cronjob and cronhpa，also it is helpful for users to understand。

Can kubernetes-cronhpa-controller provide a parameter like ‘--cron-entrys [5|6]’ or ‘--cronspec=“Minute | Hour | Dom | Month | DowOptional | Descriptor“’ ？ So，user can choose witch cron spec to use。

**Comment by ringtail** [comment]
> n kubernetes-cronhpa-controller provide a parameter like ‘--cron-entrys [5|6]’ or ‘--cronspec=“Minute | Hour | Dom | Month | DowOptional | Descriptor“’ ？ So，user can choose witch cron spec to use。

I think you can set second to * or 0 as default.
