### ISSUE TITLE
能不能加个功能，定时修改 hpa的max，有些场景要限制max的使用量，防止非关键业务在突发业务场景下面使用太多pod

### ISSUE THREAD

**Issue by zhangzhenhuajack** [AliyunContainerService/kubernetes-cronhpa-controller#95]

**Comment by zhangzhenhuajack** [comment]
因为重要业务高峰的时候，限制某些不重要服务的pod使用量；而空闲时间不重要业务的max比较大(视频合成场景)；从而可以达到节省非要的目的。

**Comment by ringtail** [comment]
是需要动态调整HPA的config对吧

**Comment by zhangzhenhuajack** [comment]
是的，目的是想通过cronhpa，按周期，同时能修改hpa的min和max

**Comment by zhangzhenhuajack** [comment]
![image](https://user-images.githubusercontent.com/11462004/126425967-d6df8280-b3ff-4f41-8d8c-a7a5ad7853f3.png)
也就是希望HorizontalPodAutoscaler这种类型的，支持targetMin和targetMax，不需要targetSize;

**Comment by vperson** [comment]
> ![image](https://user-images.githubusercontent.com/11462004/126425967-d6df8280-b3ff-4f41-8d8c-a7a5ad7853f3.png)
> 也就是希望HorizontalPodAutoscaler这种类型的，支持targetMin和targetMax，不需要targetSize;

我也遇到场景需要这个需求。

**Comment by ringtail** [comment]
> > ![image](https://user-images.githubusercontent.com/11462004/126425967-d6df8280-b3ff-4f41-8d8c-a7a5ad7853f3.png)
> > 也就是希望HorizontalPodAutoscaler这种类型的，支持targetMin和targetMax，不需要targetSize;
> 
> 我也遇到场景需要这个需求。

好的，我们设计下

**Comment by letdosomething** [comment]
> 

这个功能现在实现了吗

**Comment by ringtail** [comment]
你们的场景是什么样子的，和之前的issue是类似的吗

**Comment by letdosomething** [comment]
> 
对，类似的。预估的副本数不太准确，还是需要自动扩容。所以最好还是能定时修改hpa的上下限

**Comment by ringtail** [comment]
> 预估的副本数不太准确，还是需要自动扩容。所以最好还是能定时修改hpa的上下限

有试过我们现在的HPA+CronHPA的能力吗

**Comment by letdosomething** [comment]
> > 预估的副本数不太准确，还是需要自动扩容。所以最好还是能定时修改hpa的上下限
> 
> 有试过我们现在的HPA+CronHPA的能力吗

现在的指哪个？

**Comment by ringtail** [comment]
> > > 预估的副本数不太准确，还是需要自动扩容。所以最好还是能定时修改hpa的上下限
> > 
> > 
> > 有试过我们现在的HPA+CronHPA的能力吗
> 
> 现在的指哪个？

默认的HPA+CronHPA的行为，我还是对max的调整有些疑问。

**Comment by letdosomething** [comment]
> > > > 预估的副本数不太准确，还是需要自动扩容。所以最好还是能定时修改hpa的上下限
> > > 
> > > 
> > > 有试过我们现在的HPA+CronHPA的能力吗
> > 
> > 
> > 现在的指哪个？
> 
> 默认的HPA+CronHPA的行为，我还是对max的调整有些疑问。

现在的hpa+cronhpa，如果hpa的minReplicas设的小了，cronhpa在某个时间点完成扩容之后，服务不会缩回去吗？

**Comment by ringtail** [comment]
> 如果hpa的minReplicas设的小了，cronhpa在某个时间点完成扩容之后，服务不会缩回去吗？

缩容按照实际的容量来缩，比如HPA判断副本应该为1，CronHPA为3，那么先到3，然后HPA接管到1.

**Comment by letdosomething** [comment]
> > 如果hpa的minReplicas设的小了，cronhpa在某个时间点完成扩容之后，服务不会缩回去吗？
> 
> 缩容按照实际的容量来缩，比如HPA判断副本应该为1，CronHPA为3，那么先到3，然后HPA接管到1.

那这里理解的意思，cronhpa只是暂时把副本数抬高，而后续都是hpa管理。现在想要的还是，cronhpa抬高副本数之后，hpa只能在这个基础上往上扩而不能缩的小于这个副本数

**Comment by ringtail** [comment]
> 上往上扩而不能缩的小于这个副本数

这里取决于HPA的状态，如果是扩容，副本为3，HPA为1，那么HPA min会被置为3

**Comment by letdosomething** [comment]
> > 上往上扩而不能缩的小于这个副本数
> 
> 这里取决于HPA的状态，如果是扩容，副本为3，HPA为1，那么HPA min会被置为3

那如果缩容呢，副本数不就会小于cronhpa设定了的吗

**Comment by ringtail** [comment]
> 副本数不就会小于cronhpa设定了的吗

https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/pull/45 可以看下这个策略

**Comment by letdosomething** [comment]
> > 副本数不就会小于cronhpa设定了的吗
> 
> #45 可以看下这个策略

好的，3q。我想要的就是这个
